# code: language=ansible

---
- hosts: all
  connection: local
  become: false
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Get DNS info
      ansible.builtin.set_fact:
        nameservers: "{{ ansible_dns.nameservers }}"
        cacheable: true
      delegate_to: localhost
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Print subset of facts
      debug:
        msg: "{{ nameservers }}"
