# code: language=ansible

---
- hosts: localhost
  connection: local
  gather_facts: true
  # debugger: on_failed
  any_errors_fatal: true
  vars:
    os_environment:
      - key: EDITOR
        value: vim
  pre_tasks:
      - name: Get running ansible user
        ansible.builtin.set_fact:
          local_user: "{{ lookup('env', 'USER') }}"
          home_dir: "{{ lookup('env', 'HOME') }}"
          work_dir: "{{ playbook_dir | dirname }}"
          cacheable: true
        tags: qa

      - name: Top-level directory in project
        ansible.builtin.shell: git rev-parse --show-toplevel
        register: tld
        tags: qa

      - name: Set tld stdout fact
        ansible.builtin.set_fact:
          tld: "{{ tld.stdout }}"
        tags: qa

      - name: Get OS release
        ansible.builtin.set_fact:
          os_release: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}"
          major_ver: "{{ ansible_distribution_major_version }}"
          distro: "{{ ansible_distribution }}"
        tags: qa
  tasks:
    - name: .bashrc
      ansible.builtin.copy:
        src: "{{ tld }}/config/.bashrc.fedora"
        dest: "{{ home_dir }}/.bashrc"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0644
        backup: yes
        force: yes
      become: false
      when: ansible_os_family == "RedHat"

    - name: .bash_profile
      ansible.builtin.replace:
        path: "{{ home_dir }}/.bash_profile"
        regexp: '^\# \.bash_profile\n\n\# Get.*\nif.*\n\t\.\s.*\nfi\n\n\# User.*'
        replace: |
          [[ -s ~/.bashrc ]] && source ~/.bashrc
      become: false
      when: ansible_os_family == "RedHat"

    # https://unix.stackexchange.com/a/513413
    - name: fix networkmanager.conf hostname
      ansible.builtin.lineinfile:
        path: /etc/NetworkManager/NetworkManager.conf
        state: present
        regexp: '^\[main\]\n#plugins=.*\n'
        firstmatch: true
        line: 'hostname-mode=none'
        insertafter: '^#plugins=.*$'
      become: true
      when: ansible_os_family == "RedHat"

    - name: Create ~/.cargo directory
      ansible.builtin.file:
        path: "{{ home_dir }}/.cargo"
        state: directory
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0755
      become: false

    - name: cargo env
      ansible.builtin.copy:
        src: "{{ tld }}/config/cargo.env"
        dest: "{{ home_dir }}/.cargo/env"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0644
        force: yes
      become: false

    - name: Copy requirements.txt
      ansible.builtin.copy:
        src: "{{ tld }}/config/requirements.txt"
        dest: "{{ home_dir }}/.config/requirements.txt"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0644
        force: yes
      become: false

    - name: Install requirements.txt
      ansible.builtin.pip:
        requirements: "{{ home_dir }}/.config/requirements.txt"
        state: present
        extra_args: --user
      become: false

    - name: startup.py
      ansible.builtin.copy:
        src: "{{ tld }}/config/startup.py"
        dest: "{{ home_dir }}/.config/startup.py"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        force: yes
      become: false

    - name: fzf completion
      ansible.builtin.copy:
        src: "{{ tld }}/config/.fzf.bash"
        dest: "{{ home_dir }}/.fzf.bash"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0644
        force: yes
      become: false

    - name: Download shell-color-scripts
      ansible.builtin.git:
        repo: https://gitlab.com/dwt1/shell-color-scripts.git
        dest: "{{ home_dir }}/git/shell-color-scripts"
        version: master
        force: yes
        update: yes
        accept_hostkey: yes
      become: false

    - name: Install shell-color-scripts
      ansible.builtin.shell:
        cmd: make install
        chdir: "{{ home_dir }}/git/shell-color-scripts"
        executable: /bin/bash
      become: true

    - name: Copy .restic to home directory
      ansible.builtin.copy:
        src: "{{ tld }}/config/.restic"
        dest: "{{ home_dir }}"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        force: yes
      become: false

    - name: Copy restic-backup.service
      ansible.builtin.copy:
        src: "{{ tld }}/config/.restic/restic-backup.service"
        dest: "{{ home_dir }}/.config/systemd/user"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        force: yes
      become: false

    - name: Copy restic-backup.timer
      ansible.builtin.copy:
        src: "{{ tld }}/config/.restic/restic-backup.timer"
        dest: "{{ home_dir }}/.config/systemd/user"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        force: yes
      become: false

    - name: Enable restic backup timer
      ansible.builtin.shell: |
        systemctl --user enable --now restic-backup.timer
      become: false

    - name: Copy restic-prune.service
      ansible.builtin.copy:
        src: "{{ tld }}/config/.restic/restic-prune.service"
        dest: "{{ home_dir }}/.config/systemd/user"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        force: yes
      become: false

    - name: Copy restic-prune.timer
      ansible.builtin.copy:
        src: "{{ tld }}/config/.restic/restic-prune.timer"
        dest: "{{ home_dir }}/.config/systemd/user"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        force: yes
      become: false

    - name: Enable restic prune timer
      ansible.builtin.shell: |
        systemctl --user enable --now restic-prune.timer
      become: false

    - name: Set vm.swappiness (memory)
      ansible.builtin.sysctl:
        name: vm.swappiness
        value: 10
        state: present
        reload: yes
      become: true

    - name: Set vm.swappiness (/etc/sysctl.conf)
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        state: present
        regexp: '^vm.swappiness.*'
        line: 'vm.swappiness = 10'
        insertafter: '^#vm.swappiness.*$'
      become: true

    - name: Set vm.vfs_cache_pressure (memory)
      ansible.builtin.sysctl:
        name: vm.vfs_cache_pressure
        value: 50
        state: present
        reload: yes
      become: true

    - name: Set vm.vfs_cache_pressure (/etc/sysctl.conf)
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        state: present
        regexp: '^vm.vfs_cache_pressure.*'
        line: 'vm.vfs_cache_pressure = 50'
        insertafter: '^#vm.vfs_cache_pressure.*$'
      become: true
