# code: language=ansible

---
- name: Register ~/.gitconfig user.name and user.email
  ansible.builtin.shell: |
    git config --global user.name "{{ git_user.0.value }}"
    git config --global user.email "{{ git_user.1.value }}"

- name: Add a setting to ~/.gitconfig
  community.general.git_config:
    name: alias.amend
    scope: global
    value: commit --amend --no-edit

- name: Add a setting to ~/.gitconfig
  community.general.git_config:
    name: push.autoSetupRemote
    scope: global
    value: true

- name: Setup directory for git repos
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/git"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: false

- name: Copy ssh keys
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.ssh/{{ item | basename }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  with_items:
    - "{{ lookup('env', 'HOME') }}/.ssh/{{ ssh_key }}"
    - "{{ lookup('env', 'HOME') }}/.ssh/{{ ssh_key }}.pub"

- name: Accept GitHub ssh key fingerprint
  ansible.builtin.shell: |
    mkdir -p {{ ansible_user_dir }}/.ssh
    ssh-keyscan github.com >> {{ ansible_user_dir }}/.ssh/known_hosts
    ssh-keyscan gist.github.com >> {{ ansible_user_dir }}/.ssh/known_hosts
  changed_when: false
