# code: language=ansible

---
- name: Install Gum on macOS
  community.general.homebrew:
    name: gum
    state: latest
  become: false
  when: ansible_os_family == "Darwin"

- name: Install Gum on Debian-based systems
  block:
    - name: Add Charm GPG key to apt
      ansible.builtin.apt_key:
        url: https://repo.charm.sh/apt/gpg.key
        state: present

    - name: Add Charm repository
      ansible.builtin.apt_repository:
        repo: "deb https://repo.charm.sh/apt/ * *"
        state: present
        filename: charm

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      register: apt_update_result
      ignore_errors: yes

    - name: Handle apt update failure
      block:
        - name: Remove Charm repository if apt update fails
          ansible.builtin.file:
            path: /etc/apt/sources.list.d/charm.list
            state: absent
          when: apt_update_result is failed

        - name: Update apt cache again after removing repository
          ansible.builtin.apt:
            update_cache: yes
          when: apt_update_result is failed
      when: apt_update_result is failed

    - name: Install Gum
      ansible.builtin.apt:
        name: gum
        state: latest
  when: ansible_os_family == "Debian"

- name: Install Gum on RedHat-based systems
  block:
    - name: Add Charm repository
      ansible.builtin.yum_repository:
        name: charm
        description: Charm
        baseurl: https://repo.charm.sh/yum/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://repo.charm.sh/yum/gpg.key

    - name: Import Charm GPG key
      ansible.builtin.rpm_key:
        key: https://repo.charm.sh/yum/gpg.key
        state: present

    - name: Install Gum
      ansible.builtin.dnf:
        name: gum
        state: latest
  when: ansible_os_family == "RedHat"
