# code: language=ansible

---
- hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars:
    libvirt_user: "{{ ansible_user }}"
    libvirt_group: "libvirt"
  roles:
    - role: pre-tasks
      tags: pre

    - role: geerlingguy.swap
      swap_file_state: absent
      when: ansible_os_family == "RedHat"
      tags: pre
  tasks:
    - include_vars:
        file: vars/all.yml

    - include_tasks:
        file: git.yml
        apply:
          become_user: "{{ local_user }}"
          tags: pre

    - include_tasks:
        file: pull-repos.yml
        apply:
          become_user: "{{ local_user }}"
          tags: pre

    - name: Install common dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - qemu-kvm
        - bridge-utils
        - virt-manager

    - name: Install additional packages for Debian family
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - libvirt-clients
        - libvirt-daemon
        - libvirt-daemon-system
      when: ansible_os_family == 'Debian'

    - name: Install additional packages for RedHat family
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - libvirt
        - virt-install
      when: ansible_os_family == 'RedHat'

    - name: Increase network buffer sizes
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: 'net.core.rmem_max', value: '16777216' }
        - { name: 'net.core.wmem_max', value: '16777216' }

    - name: Increase open file descriptor limits
      community.general.pam_limits:
        domain: '*'
        limit_type: "{{ item.limit_type }}"
        limit_item: nofile
        value: 65536
      loop:
        - { limit_type: 'soft' }
        - { limit_type: 'hard' }

    - name: Setup IP forwarding in 99-ipforward.conf
      ansible.builtin.blockinfile:
        path: /etc/sysctl.d/99-ipforward.conf
        block: |
          net.ipv4.ip_forward = 1
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        marker_begin: "BEGIN"
        marker_end: "END"
        create: true
        backup: no
        state: present
      tags: qa

    - name: Set user and group in qemu.conf
      ansible.builtin.blockinfile:
        path: /etc/libvirt/qemu.conf
        block: |
          user = "{{ libvirt_user }}"
          group = "{{ libvirt_group }}"
        insertafter: '^#user = "qemu"'
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        marker_begin: "BEGIN"
        marker_end: "END"
        backup: no
        state: present

    - name: Restart libvirtd service
      ansible.builtin.systemd:
        name: libvirtd
        state: restarted
