# code: language=ansible

---
- name: Run all tasks
  hosts: all
  become: false
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/all.yml"
  tasks:
    - name: Install packages
      include_tasks:
        file: pkg.yml
        apply:
          tags: pkg
      tags: pkg

    - name: Setup git
      include_tasks:
        file: git.yml
        apply:
          tags: git
      tags: git

    - name: Pull repos
      include_tasks:
        file: pull-repos.yml
        apply:
          tags: pull
      tags: pull

    - name: Install gum
      include_tasks:
        file: gum.yml
        apply:
          tags: gum
      tags: gum

    - name: Install docker (Linux)
      include_role:
        name: geerlingguy.docker
        apply:
          vars:
            docker_add_repo: true
            docker_repo_url: https://download.docker.com/linux
            docker_users:
              - "{{ ansible_user }}"
            docker_daemon_options:
              storage-driver: "vfs"
              log-opts:
                max-size: "100m"
            docker_install_compose_plugin: true
            docker_compose_package: docker-compose-plugin
            docker_compose_package_state: present
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
      tags: docker

    - name: Install docker (macOS)
      ansible.builtin.homebrew:
        name: "{{ item }}"
        state: latest
      loop:
        - docker
        - docker-compose
      when: ansible_os_family == "Darwin"
      tags: docker

    - name: Run docker tasks
      include_tasks:
        file: docker.yml
        apply:
          tags: docker
      tags: docker

    - name: Change wallpaper (macOS)
      include_tasks:
        file: wallpaper.yml
        apply:
          vars:
            filename: "{{ playbook_dir }}/files/z-w-gu-nier.png"
          tags: wallpaper
      tags: wallpaper
