# code: language=ansible

---
- name: Run all tasks
  hosts: all
  become: false
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/all.yml"
  tasks:
    - name: Install packages
      include_tasks:
        file: pkg.yml
        apply:
          tags: pkg
      tags: pkg

    - name: Setup git
      include_tasks:
        file: git.yml
        apply:
          tags: git
      tags: git

    - name: Pull repos
      include_tasks:
        file: pull-repos.yml
        apply:
          tags: pull
      tags: pull

    - name: Install gum
      include_tasks:
        file: gum.yml
        apply:
          become: true
          tags: gum
      tags: gum

    - name: Run docker tasks
      include_tasks:
        file: docker.yml
        apply:
          become: true
          tags: docker
      tags: docker

    - name: Change wallpaper (macOS)
      include_tasks:
        file: wallpaper.yml
        apply:
          vars:
            filename: "{{ playbook_dir }}/files/z-w-gu-nier.png"
          tags: wallpaper
      tags: wallpaper
