# code: language=ansible

---
- name: Test Playbook
  hosts: all
  tasks:
    - name: Test ping
      ansible.builtin.ping:
      register: result

    - name: Print ping result
      ansible.builtin.debug:
        msg: "{{ result }}"
