# code: language=ansible

---
- name: Update Package Cache (Debian)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  register: apt_get_status
  until: apt_get_status is success
  retries: 3
  delay: 5
  become: true
  when: ansible_os_family == "Debian"

- name: Update Package Cache (Red Hat)
  ansible.builtin.dnf:
    update_cache: yes
  register: dnf_status
  until: dnf_status is success
  retries: 3
  delay: 5
  become: true
  when: ansible_os_family == "RedHat"

- name: |
    Add git-core PPA
    DESC [Add the git-core PPA to install the latest version of git
  ansible.builtin.apt_repository:
    repo: "ppa:git-core/ppa"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Cross-platform dependencies
  ansible.builtin.package:
    name:
      - acl
      - ca-certificates
      - curl
      - git
      - make
      - python3
      - python3-pip
      - python3-psutil
      - python3-redis
      - tree
      - unzip
      - vim
      - wget
    state: present
  changed_when: false
  become: true
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

- name: Install Red Hat packages
  ansible.builtin.dnf:
    name:
      - "@Development tools"
      - bzip2
      - gcc
      - python3
      - python3-devel
      - python3-setuptools
      - python3-virtualenv
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Install debian packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - autoconf
      - gnupg-agent
      - jq
      - software-properties-common
    update_cache: yes
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Setup ~/.local/bin directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: false
