# code: language=ansible

---
- debug:
    msg: "Use within a parent playbook as an include_tasks directive."

- name: Update Package Cache (Debian)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  register: apt_get_status
  until: apt_get_status is success
  retries: 3
  delay: 5
  become: true
  when: ansible_os_family == "Debian"

- name: Update Package Cache (Red Hat)
  ansible.builtin.dnf:
    update_cache: yes
  register: dnf_status
  until: dnf_status is success
  retries: 3
  delay: 5
  become: true
  when: ansible_os_family == "RedHat"

- name: |
    Add git-core PPA
    DESC [Add the git-core PPA to install the latest version of git
  ansible.builtin.apt_repository:
    repo: "ppa:git-core/ppa"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Cross-platform dependencies
  ansible.builtin.package:
    name:
      - acl
      - ansible
      - ansible-lint
      - bat
      - ca-certificates
      - cloud-init
      - curl
      - fpart
      - git
      - make
      - nginx
      - python3
      - python3-certbot-nginx
      - python3-pip
      - python3-psutil
      - python3-redis
      - redis
      - tree
      - unzip
      - vim
      - wget
      - which
    state: present
  changed_when: false
  become: true

- name: Install Red Hat packages
  ansible.builtin.dnf:
    name:
      - "@Development tools"
      - bzip2
      - gcc
      - gdbm-devel
      - libffi-devel
      - libyaml-devel
      - ncurses-devel
      - openssl-devel
      - patch
      - python3
      - python3-devel
      - python3-pip
      - python3-setuptools
      - python3-virtualenv
      - readline-devel
      - rust
      - zlib-devel
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Install debian packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - autoconf
      - bats
      - build-essential
      - gnupg-agent
      - jq
      - kafkacat
      - libbz2-dev
      - libdb-dev
      - libffi-dev
      - libffi-dev
      - libgdbm-dev
      - libgdbm6
      - libgmp-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libreadline6-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libyaml-dev
      - llvm
      - moreutils
      - net-tools
      - nfs-kernel-server
      - patch
      - python3
      - python3-pip
      - rustc
      - software-properties-common
      - tk-dev
      - tree
      - uuid-dev
      - xfsprogs
      - xz-utils
      - zlib1g-dev
    update_cache: yes
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Setup ~/.local/bin directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: false
