# code: language=ansible

---
- name: Set wallpaper using osascript
  command: >
    osascript -e 'tell application "System Events" to tell every desktop to set picture to POSIX file "{{ filename }}"'
  when: ansible_os_family == "Darwin"
